spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/trackTime
    username: root
    password: 123
server:
  port: 8180
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG